name: check

on:
  pull_request:
    branches: [ '*' ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
      - name: Install Dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test 
        run: go test 
      
