name: check

on:
  pull_request:
    branches: [ '*' ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
      - name: Install golangci-lint
        run: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3 # Use a specific version
    #   - name: Run golangci-lint
    #     run: golangci-lint run
      - name: Install Dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test 
        run: go test 
      
